name: Build & Publish Docker Image

on:
  push:
    branches:    
      - tgmc-master

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build & Publish Docker Image
    steps:
    - name: Configure environment
      id: config
      run: |
        SHA=$(echo ${GITHUB_SHA:0:8})
        DEFAULT=$(echo $GITHUB_REF | sed -e "s/^refs\/tags//")
        if [ ! -z $DEFAULT ]; then
          VERSION=${DEFAULT}-tgmc-${SHA}
        else
          VERSION=tgmc-${SHA}
        fi
        echo ::set-output name=version::$VERSION

    - name: Checkout
      uses: actions/checkout@tgmc-master

    - name: Publish docker
      id: docker
      uses: zenato/docker-action@master
      with:
        username: ${{ secrets.ALIYUN_DOCKER_USERNAME }}
        password: ${{ secrets.ALIYUN_DOCKER_PASSWORD }}
        repository: clinico-omics/metabase
        registry: registry.cn-shanghai.aliyuncs.com/pgx-docker-registry
        tag: ${{ steps.config.outputs.version }}

    - name: Print the name of built image
      run: echo "${{steps.docker.outputs.image}}"