name: Build & Publish Docker Image

on:
  push:
    branches:    
      - tgmc-master

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build & Publish Docker Image
    steps:
    - name: Configure environment
      id: config
      run: |
        SHA=$(echo ${GITHUB_SHA:0:8})
        TAG=$(echo $GITHUB_REF | sed -e "s/^refs\/tags//")
        INVALID_TAG=$(echo $TAG | grep "/" )
        echo "TAG: ${TAG}, INVALID_TAG: ${INVALID_TAG}, SHA: ${SHA}"
        if [ -z $INVALID_TAG ]; then
          VERSION=${TAG}-tgmc-${SHA}
        else
          VERSION=tgmc-${SHA}
        fi
        echo "VERSION: ${VERSION}"
        echo ::set-output name=version::$VERSION

    - name: Checkout
      uses: actions/checkout@master

    - name: Publish docker
      id: docker
      uses: zenato/docker-action@master
      with:
        username: ${{ secrets.ALIYUN_DOCKER_USERNAME }}
        password: ${{ secrets.ALIYUN_DOCKER_PASSWORD }}
        repository: metabase
        registry: registry.cn-shanghai.aliyuncs.com/pgx-docker-registry
        tag: ${{ steps.config.outputs.version }}

    - name: Print the name of built image
      run: echo "${{steps.docker.outputs.image}}"

    - name: Dingtalk Robot Message
      uses: fifsky/dingtalk-action@master
      with:
        url: ${{ secrets.DINGTALK_WEBHOOK }}
        type: markdown
        content: |
          # Metabase镜像自动构建通知
          @Choppy Team 主人，我已将您刚更新在Github上的Metabase代码，构建成Docker镜像发布到阿里云镜像仓库了，请您随时取用
          > Choppy Team：可登录 https://github.com/clinico-omics/metabase 查看详情
        at: Choppy Team